import { Tome } from './cgi-types';

export const CGI_TOME_2: Tome = {
  tome: 2,
  titre: 'Enregistrement, Timbre, Curatelle et Textes fiscaux',
  livres: [
    {
      livre: 1,
      titre: 'Enregistrement des actes et mutations',
      page: 149,
      chapitres: [
        { chapitre: 1, titre: 'De l\'enregistrement', page: 149 },
        { chapitre: 2, titre: 'Assiette des droits', page: 151 },
        { chapitre: 3, titre: 'Délais pour l\'enregistrement', page: 158 },
        { chapitre: 4, titre: 'Bureaux d\'enregistrement', page: 162 },
        { chapitre: 5, titre: 'Paiement des droits', page: 162 },
        { chapitre: 6, titre: 'Peines pour défaut d\'enregistrement dans les délais', page: 164 },
        { chapitre: 7, titre: 'Insuffisances et dissimulations', page: 167 },
        { chapitre: 8, titre: 'Obligations des parties', page: 169 },
        { chapitre: 9, titre: 'Droits acquis et prescriptions, restitutions ou remboursements', page: 179 },
        { chapitre: 10, titre: 'Poursuites et instances', page: 181 },
        { chapitre: 11, titre: 'Fixation des droits', page: 182 },
        { chapitre: 12, titre: 'Enregistrement en débit, enregistrement gratis et exemptions', page: 193 },
        { chapitre: 13, titre: 'Taxe spéciale sur les assurances', page: 200 },
        { chapitre: 14, titre: 'Actes passés hors du Congo', page: 203 },
        { chapitre: 15, titre: 'Sommes et valeurs atteintes par la prescription', page: 203 },
        { chapitre: 16, titre: 'Formalité unique', page: 203 },
      ],
    },
    {
      livre: 2,
      titre: 'Contribution du timbre',
      page: 205,
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales', page: 205 },
        { chapitre: 2, titre: 'Timbre de dimension', page: 208 },
        { chapitre: 3, titre: 'Timbres des passeports, cartes d\'identité, carnets de séjour', page: 211 },
        { chapitre: 4, titre: 'Visa spécial, timbre en débit et actes exempts de timbre', page: 212 },
        { chapitre: 5, titre: 'Droits de timbre des effets de commerce', page: 219 },
        { chapitre: 6, titre: 'Droit de timbre sur les véhicules automobiles, droits de timbre non codifiés', page: 221 },
      ],
    },
    {
      livre: 3,
      titre: 'Impôt sur le revenu des valeurs mobilières (IRVM)',
      page: 222,
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales', page: 222 },
        { chapitre: 2, titre: 'Dispositions diverses', page: 226 },
        { chapitre: 3, titre: 'Exemptions', page: 226 },
        { chapitre: 4, titre: 'Déclarations et pièces à déposer par les sociétés', page: 230 },
      ],
    },
    {
      livre: 4,
      titre: 'Taxe immobilière',
      page: 231,
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales', page: 231 },
        { chapitre: 2, titre: 'Modalités d\'imposition', page: 231 },
      ],
    },
    {
      livre: 5,
      titre: 'Curatelle',
      page: 233,
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales', page: 233 },
        { chapitre: 2, titre: 'Des curateurs et de leurs attributions', page: 233 },
        { chapitre: 3, titre: 'Obligations des curateurs à l\'ouverture d\'une succession', page: 234 },
        { chapitre: 4, titre: 'Vente du mobilier et des immeubles', page: 235 },
        { chapitre: 5, titre: 'Obligations', page: 236 },
        { chapitre: 6, titre: 'Successions et biens vacants des étrangers', page: 236 },
        { chapitre: 7, titre: 'Gestion avec les tiers', page: 236 },
        { chapitre: 8, titre: 'Remise des successions au domaine et vente des biens non réclamés', page: 236 },
        { chapitre: 9, titre: 'Comptabilité des successions et biens vacants', page: 237 },
        { chapitre: 10, titre: 'Surveillance administrative et apurement des comptes des curateurs', page: 238 },
        { chapitre: 11, titre: 'Conseil de curatelle', page: 239 },
        { chapitre: 12, titre: 'Fonds de prévoyance', page: 239 },
        { chapitre: 13, titre: 'Enregistrement – Timbre – Frais de procédure', page: 239 },
        { chapitre: 14, titre: 'Biens sous séquestre', page: 239 },
      ],
    },
    { livre: 6, titre: 'Taxe sur le kilowatt/heure', page: 239, statut: 'abrogé' },
    { livre: 7, titre: 'Taxe sur les appareils automatiques', page: 240 },
    { livre: 8, titre: 'Droits relatifs aux domaines de l\'État', page: 240 },
  ],
  sectionsNonCodifiees: [
    {
      section: 1,
      titre: 'Conventions fiscales',
      page: 241,
      contenu: [
        { code: '1.1', titre: 'Convention fiscale CEMAC', page: 241 },
        { code: '1.2', titre: 'Convention fiscale avec la Chine', page: 261 },
        { code: '1.3', titre: 'Convention fiscale avec la France', page: 274 },
        { code: '1.4', titre: 'Convention fiscale avec l\'Italie', page: 290 },
        { code: '1.5', titre: 'Convention fiscale avec la République de Maurice', page: 305 },
        { code: '1.6', titre: 'Convention fiscale avec le Rwanda', page: 319 },
      ],
    },
    {
      section: 2,
      titre: 'Textes relatifs aux investissements',
      page: 337,
      contenu: [
        { code: '2.1', titre: 'Charte des investissements', page: 337 },
        { code: '2.2', titre: 'Modalités d\'agrément des entreprises', page: 344 },
        { code: '2.3', titre: 'Zones économiques spéciales (ZES)', page: 352 },
        { code: '2.4', titre: 'Zones franches de santé', page: 360 },
        { code: '2.5', titre: 'Zone de valorisation des infrastructures immobilières marchandes', page: 361 },
        { code: '2.6', titre: 'Encouragement à l\'entrepreneuriat', page: 363 },
        { code: '2.7', titre: 'Opérations sur titres admis à la cote de la BVMAC', page: 364 },
      ],
    },
    {
      section: 3,
      titre: 'Fiscalité des mines et des hydrocarbures',
      page: 368,
      contenu: [
        { code: '3.1', titre: 'Dispositions fiscales du Code des hydrocarbures', page: 368 },
        { code: '3.2', titre: 'Redevance superficiaire', page: 374 },
        { code: '3.3', titre: 'Application des dispositions fiscales au secteur pétrolier amont', page: 375 },
        { code: '3.4', titre: 'Modalités d\'application de la TVA au secteur pétrolier', page: 397 },
        {
          code: '3.5',
          titre: 'Fiscalité minière',
          page: 402,
          details: [
            { code: '3.5.1', titre: 'Dispositions fiscales du Code minier', page: 402 },
            { code: '3.5.2', titre: 'Taux et règles de perception des droits sur les titres miniers', page: 406 },
          ],
        },
      ],
    },
    {
      section: 4,
      titre: 'Impôts, taxes et retenues divers',
      page: 408,
      contenu: [
        { code: '4.1', titre: 'Acompte sur divers impôts (ASDI)', page: 408 },
        { code: '4.2', titre: 'Contribution de solidarité pour la CAMU', page: 410 },
        {
          code: '4.3', titre: 'Droits d\'accises et taxes assimilées', page: 411,
          details: [
            { code: '4.3.1', titre: 'Droits d\'accises', page: 411 },
            { code: '4.3.2', titre: 'Taxe spécifique sur les boissons et le tabac', page: 412 },
          ],
        },
        {
          code: '4.4', titre: 'Droits fonciers exceptionnels', page: 413,
          details: [
            { code: '4.4.1', titre: 'Institution de droits fonciers exceptionnels', page: 413 },
            { code: '4.4.2', titre: 'Frais de travaux cadastraux', page: 418 },
          ],
        },
        { code: '4.5', titre: 'Impôt forfaitaire sur les pylônes des sociétés de télécommunication', page: 419 },
        { code: '4.6', titre: 'Impôt global forfaitaire (IGF)', page: 420 },
        { code: '4.7', titre: 'Redevance audiovisuelle et d\'électrification rurale', page: 422 },
        { code: '4.8', titre: 'Retenue à la source sur les sommes payées par le Trésor public', page: 423 },
        { code: '4.9', titre: 'Taxe d\'abonnement et de branchement télévisuel', page: 424 },
        { code: '4.10', titre: 'Taxe d\'occupation des locaux', page: 425 },
        { code: '4.11', titre: 'Taxe sur le trafic des communications électroniques', page: 427 },
        { code: '4.12', titre: 'Taxe sur les billets d\'avion vols internationaux', page: 428 },
        { code: '4.13', titre: 'Taxe sur les jeux de hasard', page: 429 },
        { code: '4.14', titre: 'Taxe sur les transferts de fonds', page: 430 },
        { code: '4.15', titre: 'Taxe unique sur les salaires', page: 434 },
        { code: '4.16', titre: 'Taxe sur les emballages non récupérables', page: 436 },
      ],
    },
    {
      section: 5,
      titre: 'Obligations et procédures fiscales non codifiées',
      page: 437,
      contenu: [
        { code: '5.1', titre: 'Attestation de non-redevance fiscale', page: 437 },
        {
          code: '5.2', titre: 'Numéro d\'identification unique (NIU)', page: 438,
          details: [
            { code: '5.2.1', titre: 'Décret n°2004-469 du 3 novembre 2004', page: 438 },
            { code: '5.2.2', titre: 'Arrêté n°5327 du 12 mars 2020', page: 438 },
            { code: '5.2.3', titre: 'Arrêté n°25604 du 29 octobre 2022', page: 440 },
          ],
        },
        { code: '5.3', titre: 'Recouvrement des recettes publiques', page: 442 },
        { code: '5.4', titre: 'Approche fondée sur les risques pour l\'exécution des contrôles fiscaux', page: 445 },
        { code: '5.5', titre: 'Échange des renseignements avec les administrations fiscale et douanière', page: 448 },
      ],
    },
    {
      section: 6,
      titre: 'Taxe sur la valeur ajoutée (TVA)',
      page: 453,
      contenu: [
        { code: '6.1', titre: 'Champ d\'application', page: 453 },
        { code: '6.2', titre: 'Fait générateur et exigibilité', page: 459 },
        { code: '6.3', titre: 'Base d\'imposition et taux', page: 460 },
        { code: '6.4', titre: 'Régime des déductions', page: 462 },
        { code: '6.5', titre: 'Modalités pratiques', page: 464 },
      ],
    },
  ],
  annexes: { titre: 'Index', page: 471 },
};
