import { Tome } from './cgi-types';

/**
 * CGI 2026 - Tome 2 : Enregistrement, Timbre, Curatelle et Textes fiscaux
 */
export const CGI_TOME_2_2026: Tome = {
  tome: 2,
  titre: 'Enregistrement, Timbre, Curatelle et Textes fiscaux',
  livres: [
    {
      livre: 1,
      titre: 'Enregistrement des actes et mutations',
      chapitres: [
        { chapitre: 1, titre: 'De l\'enregistrement' },
        { chapitre: 2, titre: 'Assiette des droits' },
        { chapitre: 3, titre: 'Délais pour l\'enregistrement' },
        { chapitre: 4, titre: 'Bureaux d\'enregistrement' },
        { chapitre: 5, titre: 'Paiement des droits' },
        { chapitre: 6, titre: 'Peines pour défaut d\'enregistrement dans les délais' },
        { chapitre: 7, titre: 'Insuffisances et dissimulations' },
        { chapitre: 8, titre: 'Obligations des parties' },
        { chapitre: 9, titre: 'Droits acquis et prescriptions, restitutions ou remboursements' },
        { chapitre: 10, titre: 'Poursuites et instances' },
        { chapitre: 11, titre: 'Fixation des droits' },
        { chapitre: 12, titre: 'Enregistrement en débit, enregistrement gratis et exemptions' },
        { chapitre: 13, titre: 'Taxe spéciale sur les assurances' },
        { chapitre: 14, titre: 'Actes passés hors du Congo' },
        { chapitre: 15, titre: 'Sommes et valeurs atteintes par la prescription' },
        { chapitre: 16, titre: 'Formalité unique' },
      ],
    },
    {
      livre: 2,
      titre: 'Contribution du timbre',
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales' },
        { chapitre: 2, titre: 'Timbre de dimension' },
        { chapitre: 3, titre: 'Timbres des passeports, cartes d\'identité, carnets de séjour' },
        { chapitre: 4, titre: 'Visa spécial, timbre en débit et actes exempts de timbre' },
        { chapitre: 5, titre: 'Droits de timbre des effets de commerce' },
        { chapitre: 6, titre: 'Droit de timbre sur les véhicules automobiles' },
      ],
    },
    {
      livre: 3,
      titre: 'Impôt sur le revenu des valeurs mobilières (IRVM)',
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales' },
        { chapitre: 2, titre: 'Dispositions diverses' },
        { chapitre: 3, titre: 'Exemptions' },
        { chapitre: 4, titre: 'Déclarations et pièces à déposer par les sociétés' },
      ],
    },
    {
      livre: 4,
      titre: 'Taxe immobilière',
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales' },
        { chapitre: 2, titre: 'Modalités d\'imposition' },
      ],
    },
    {
      livre: 5,
      titre: 'Curatelle',
      chapitres: [
        { chapitre: 1, titre: 'Dispositions générales' },
        { chapitre: 2, titre: 'Des curateurs et de leurs attributions' },
        { chapitre: 3, titre: 'Obligations des curateurs à l\'ouverture d\'une succession' },
        { chapitre: 4, titre: 'Vente du mobilier et des immeubles' },
        { chapitre: 5, titre: 'Obligations' },
        { chapitre: 6, titre: 'Successions et biens vacants des étrangers' },
        { chapitre: 7, titre: 'Gestion avec les tiers' },
        { chapitre: 8, titre: 'Remise des successions au domaine et vente des biens non réclamés' },
        { chapitre: 9, titre: 'Comptabilité des successions et biens vacants' },
        { chapitre: 10, titre: 'Surveillance administrative et apurement des comptes des curateurs' },
        { chapitre: 11, titre: 'Conseil de curatelle' },
        { chapitre: 12, titre: 'Fonds de prévoyance' },
        { chapitre: 13, titre: 'Enregistrement – Timbre – Frais de procédure' },
        { chapitre: 14, titre: 'Biens sous séquestre' },
      ],
    },
    { livre: 6, titre: 'Taxe sur le kilowatt/heure', statut: 'abrogé' },
    { livre: 7, titre: 'Taxe sur les appareils automatiques' },
    { livre: 8, titre: 'Droits relatifs aux domaines de l\'État' },
  ],
  sectionsNonCodifiees: [
    {
      section: 1,
      titre: 'Conventions fiscales',
      contenu: [
        { code: '1.1', titre: 'Convention fiscale CEMAC' },
        { code: '1.2', titre: 'Convention fiscale avec la Chine' },
        { code: '1.3', titre: 'Convention fiscale avec la France' },
        { code: '1.4', titre: 'Convention fiscale avec l\'Italie' },
        { code: '1.5', titre: 'Convention fiscale avec la République de Maurice' },
        { code: '1.6', titre: 'Convention fiscale avec le Rwanda' },
      ],
    },
    {
      section: 2,
      titre: 'Textes relatifs aux investissements',
      contenu: [
        { code: '2.1', titre: 'Charte des investissements' },
        { code: '2.2', titre: 'Modalités d\'agrément des entreprises' },
        { code: '2.3', titre: 'Zones économiques spéciales (ZES)' },
        { code: '2.4', titre: 'Zones franches de santé' },
        { code: '2.5', titre: 'Zone de valorisation des infrastructures immobilières marchandes' },
        { code: '2.6', titre: 'Encouragement à l\'entrepreneuriat' },
        { code: '2.7', titre: 'Opérations sur titres admis à la cote de la BVMAC' },
      ],
    },
    {
      section: 3,
      titre: 'Fiscalité des mines et des hydrocarbures',
      contenu: [
        { code: '3.1', titre: 'Dispositions fiscales du Code des hydrocarbures' },
        { code: '3.2', titre: 'Redevance superficiaire' },
        { code: '3.3', titre: 'Application des dispositions fiscales au secteur pétrolier amont' },
        { code: '3.4', titre: 'Modalités d\'application de la TVA au secteur pétrolier' },
        { code: '3.5', titre: 'Fiscalité minière' },
      ],
    },
    {
      section: 4,
      titre: 'Impôts, taxes et retenues divers',
      contenu: [
        { code: '4.1', titre: 'Acompte sur divers impôts (ASDI)' },
        { code: '4.2', titre: 'Contribution de solidarité pour la CAMU' },
        { code: '4.3', titre: 'Droits d\'accises et taxes assimilées' },
        { code: '4.4', titre: 'Droits fonciers exceptionnels' },
        { code: '4.5', titre: 'Impôt forfaitaire sur les pylônes des sociétés de télécommunication' },
        { code: '4.6', titre: 'Impôt global forfaitaire (IGF)' },
        { code: '4.7', titre: 'Redevance audiovisuelle et d\'électrification rurale' },
        { code: '4.8', titre: 'Retenue à la source sur les sommes payées par le Trésor public' },
        { code: '4.9', titre: 'Taxe d\'abonnement et de branchement télévisuel' },
        { code: '4.10', titre: 'Taxe d\'occupation des locaux' },
        { code: '4.11', titre: 'Taxe sur le trafic des communications électroniques' },
        { code: '4.12', titre: 'Taxe sur les billets d\'avion vols internationaux' },
        { code: '4.13', titre: 'Taxe sur les jeux de hasard' },
        { code: '4.14', titre: 'Taxe sur les transferts de fonds' },
        { code: '4.15', titre: 'Taxe unique sur les salaires' },
        { code: '4.16', titre: 'Taxe sur les emballages non récupérables' },
      ],
    },
    {
      section: 5,
      titre: 'Obligations et procédures fiscales non codifiées',
      contenu: [
        { code: '5.1', titre: 'Attestation de non-redevance fiscale' },
        { code: '5.2', titre: 'Numéro d\'identification unique (NIU)' },
        { code: '5.3', titre: 'Recouvrement des recettes publiques' },
        { code: '5.4', titre: 'Approche fondée sur les risques pour l\'exécution des contrôles fiscaux' },
        { code: '5.5', titre: 'Échange des renseignements avec les administrations fiscale et douanière' },
      ],
    },
    {
      section: 6,
      titre: 'Taxe sur la valeur ajoutée (TVA)',
      contenu: [
        { code: '6.1', titre: 'Champ d\'application et assujettis' },
        { code: '6.2', titre: 'Territorialité' },
        { code: '6.3', titre: 'Fait générateur et exigibilité' },
        { code: '6.4', titre: 'Base d\'imposition' },
        { code: '6.5', titre: 'Taux' },
        { code: '6.6', titre: 'Déductions et régularisations' },
        { code: '6.7', titre: 'Obligations déclaratives' },
        { code: '6.8', titre: 'Déclaration, paiement et recouvrement' },
      ],
    },
  ],
  annexes: { titre: 'Annexes', page: 471 },
};
