// server/src/config/article-metadata-il.ts
// Métadonnées des articles Impôts Locaux (Partie 2 Titre 1 Chapitre 1) - CGI 2025

export interface ArticleMetadataIL {
  numero: string;
  titre: string;
  section: string;
  impot: 'generalites' | 'cfpb' | 'cfpnb' | 'dispositions_communes' | 'patente' | 'taxe_regionale' | 'spectacles';
  themes: string[];
  priority: number;
  statut: 'en_vigueur' | 'abroge';
}

/**
 * Métadonnées complètes des articles Impôts Locaux (68 articles en vigueur sur 92)
 */
export const ARTICLE_METADATA_IL: ArticleMetadataIL[] = [
  // ==================== SECTION 1: GÉNÉRALITÉS ====================
  {
    numero: 'Art. 250',
    titre: 'Répartition du produit des impôts locaux',
    section: 'Généralités',
    impot: 'generalites',
    themes: ['répartition', '85% collectivités', '10% administration', '5% chambres commerce'],
    priority: 1,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 2: CFPB ====================
  {
    numero: 'Art. 251',
    titre: 'Champ d\'application CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['propriétés bâties', 'constructions', 'champ application'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 252',
    titre: 'Redevable CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['propriétaire', 'usufruitier', 'redevable'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 252 bis',
    titre: 'Propriétés imposables CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['propriétés imposables', 'constructions', 'installations'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 253',
    titre: 'Exemptions permanentes CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['exemptions permanentes', 'État', 'édifices culte', 'bâtiments agricoles', 'ambassades'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 254',
    titre: 'Exemptions temporaires CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['exemptions temporaires', '5 ans', '10 ans', '25 ans', 'constructions nouvelles', 'habitation', 'logement personnel'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 257',
    titre: 'Base imposable CFPB - Valeur locative',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['base imposable', 'valeur locative', '75% déduction', 'revenu cadastral'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 257 bis',
    titre: 'Détermination valeur locative CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['valeur locative', 'loyer', 'évaluation'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 258',
    titre: 'Zones tarifaires CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['zones tarifaires', '250 FCFA', '150 FCFA', '25 FCFA', '12,5 FCFA', 'prix m²'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 258 bis',
    titre: 'Réduction par étage CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['réduction étage', '50% par étage', 'immeuble multi-étages'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 258 ter',
    titre: 'Taux CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['taux', '20% maximum', '1 000 FCFA minimum'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 260',
    titre: 'Fait générateur CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['fait générateur', '1er janvier', 'déclaration'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 261',
    titre: 'Avis d\'imposition CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['avis imposition', 'notification', 'rôle'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 262',
    titre: 'Paiement et réclamation CFPB',
    section: 'Contribution foncière des propriétés bâties',
    impot: 'cfpb',
    themes: ['paiement', 'réclamation', 'délai'],
    priority: 2,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 3: CFPNB ====================
  {
    numero: 'Art. 263',
    titre: 'Champ d\'application CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['propriétés non bâties', 'terrains', 'champ application'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 264',
    titre: 'Distinction terrains urbains/ruraux',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['terrains urbains', 'terrains ruraux', 'périmètre urbain'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 265',
    titre: 'Exemptions permanentes CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['exemptions permanentes', 'État', 'voies ferrées', 'cimetières'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 266',
    titre: 'Exemptions temporaires CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['exemptions temporaires', 'plantations', 'élevage', '6 ans', '10 ans', '8 ans', '7 ans', '3 ans'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 267',
    titre: 'Déclaration CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['déclaration', 'avant 1er octobre', 'exonération'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 268',
    titre: 'Défaut de déclaration CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['défaut déclaration', 'sanctions'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 270',
    titre: 'Base imposable CFPNB urbain',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['base imposable', '50%', 'valeur cadastrale', 'zones tarifaires', '125 FCFA', '75 FCFA'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 270 bis',
    titre: 'Tarifs CFPNB rural',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['tarifs ruraux', 'hectare', '2 000 FCFA', '1 000 FCFA', '600 FCFA', 'forêt', 'élevage'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 272',
    titre: 'Taux CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['taux', '40% maximum', '1 000 FCFA minimum'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 273',
    titre: 'Redevable CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['redevable', 'propriétaire', 'possesseur'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 274',
    titre: 'Avis d\'imposition CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['avis imposition', 'notification'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 275',
    titre: 'Paiement et réclamation CFPNB',
    section: 'Contribution foncière des propriétés non bâties',
    impot: 'cfpnb',
    themes: ['paiement', 'réclamation'],
    priority: 2,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 4: DISPOSITIONS COMMUNES ====================
  {
    numero: 'Art. 276',
    titre: 'Déclaration locataires',
    section: 'Dispositions communes aux sections 2 et 3',
    impot: 'dispositions_communes',
    themes: ['déclaration locataires', 'valeur locative', 'avant 1er octobre'],
    priority: 2,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 5: PATENTE ====================
  {
    numero: 'Art. 277',
    titre: 'Champ d\'application patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['champ application', 'activité commerciale', 'activité industrielle', 'profession'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 278',
    titre: 'Assiette patente - Chiffre d\'affaires',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['assiette', 'chiffre affaires', 'base imposable'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 279',
    titre: 'Exemptions patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['exemptions', 'artistes', 'pêcheurs', 'mutuelles', 'coopératives'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 281',
    titre: 'Entité fiscale patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['entité fiscale', 'établissement', 'succursale'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 282',
    titre: 'Titre de patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['titre patente', 'document', 'justificatif'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 285',
    titre: 'Affichage patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['affichage', 'obligation', 'visibilité'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 287',
    titre: 'Début d\'activité',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['début activité', 'annuité', 'prorata'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 289',
    titre: 'Cessation d\'activité',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['cessation', 'arrêt activité', 'déclaration'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 290',
    titre: 'Transfert d\'établissement',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['transfert', 'déménagement', 'changement adresse'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 291',
    titre: 'Extension d\'activité',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['extension', 'nouvelle activité'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 292',
    titre: 'Réduction d\'activité',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['réduction', 'diminution activité'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 293',
    titre: 'Sanctions patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['sanctions', 'pénalités', 'amendes'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 294',
    titre: 'Sociétés étrangères - Marchés publics',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['sociétés étrangères', 'marchés publics', '15 jours', 'patente provisoire'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 295',
    titre: 'Marchands ambulants',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['ambulants', 'forains', 'commerce itinérant'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 296',
    titre: 'Transporteurs',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['transporteurs', 'transport fluvial', 'navigation'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 297',
    titre: 'Sociétés pétrolières',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['sociétés pétrolières', '50% droits', 'pétrole'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 301',
    titre: 'Matrices patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['matrices', 'établissement rôle'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 302',
    titre: 'Contenu matrices',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['matrices', 'informations', 'données'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 303',
    titre: 'Rôle patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['rôle', 'émission', 'titre exécutoire'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 304',
    titre: 'Titre de perception',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['titre perception', 'recouvrement'],
    priority: 3,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 305',
    titre: 'Paiement patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['paiement', '10-20 avril', 'paiement fractionné', '100 000 FCFA'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 306',
    titre: 'Retard de paiement',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['retard', '100% pénalité', 'majoration'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 307',
    titre: 'Stand-by',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['stand-by', '25%', 'activité intermittente', 'mise en sommeil'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 308',
    titre: 'Déclarations patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['déclarations', 'obligations déclaratives'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 309',
    titre: 'Délai déclaration',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['délai', 'déclaration', '15 jours'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 310',
    titre: 'Contrôle patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['contrôle', 'vérification', 'droit communication'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 311',
    titre: 'Entrepôt non déclaré',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['entrepôt', '500 000 FCFA', 'amende'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 312',
    titre: 'Déclaration chiffre d\'affaires',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['déclaration CA', '30 avril', 'IS forfaitaire'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 313',
    titre: 'Sanctions défaut déclaration',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['sanctions', 'défaut déclaration', 'pénalités'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 314',
    titre: 'Barème patente',
    section: 'Contribution des patentes',
    impot: 'patente',
    themes: ['barème', 'taux progressif', '0,750%', '0,650%', '0,450%', '0,200%', '0,150%', '0,140%', '0,135%', '0,125%', '0,045%', '10 000 FCFA minimum'],
    priority: 1,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 7: TAXE RÉGIONALE ====================
  {
    numero: 'Art. 321',
    titre: 'Champ d\'application taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['personnes physiques', '18 ans', 'champ application'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 322',
    titre: 'Lieu d\'imposition taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['résidence', 'domicile', 'lieu imposition'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 323',
    titre: 'Exemptions taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['exemptions', 'diplomates', 'aveugles', 'mutilés guerre', 'indigents'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 324',
    titre: 'Recouvrement taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['recouvrement', 'rôle nominatif', '120 000 FCFA'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 325',
    titre: 'Précompte employeur',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['précompte', 'employeur', 'janvier', 'retenue'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 326',
    titre: 'Tarifs taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['tarifs', 'montant', 'barème'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 327',
    titre: 'Paiement taxe régionale',
    section: 'Taxe régionale',
    impot: 'taxe_regionale',
    themes: ['paiement', 'délai', 'modalités'],
    priority: 2,
    statut: 'en_vigueur',
  },

  // ==================== SECTION 9: TAXE SUR LES SPECTACLES ====================
  {
    numero: 'Art. 331',
    titre: 'Champ d\'application spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['spectacles', 'jeux', 'divertissements', 'champ application'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 332',
    titre: 'Exemptions spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['exemptions', 'manifestations sportives', 'spectacles éducatifs', 'fêtes patronales'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 333',
    titre: 'Tarifs spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['tarifs', '15%', '30%', '200 FCFA entrée'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 334',
    titre: 'Bars-dancings',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['bars dancings', 'musiciens', 'pick-up', '240 000 FCFA', '100 000 FCFA'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 335',
    titre: 'Salles de bal',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['salle bal', '4 000 FCFA', 'bal public'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 336',
    titre: 'Cercles privés',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['cercles privés', '10% recettes', 'clubs'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 337',
    titre: 'Appareils de jeux',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['appareils jeux', 'baby-foot', 'billard', 'jeux automatiques'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 338',
    titre: 'Billets d\'entrée',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['billets entrée', 'tickets', 'contremarques'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 339',
    titre: 'Paiement taxe spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['paiement', 'versement', 'délai'],
    priority: 2,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 340',
    titre: 'Déclarations spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['déclaration', '24h avant', 'relevé recettes', '15 jours', 'spectacle occasionnel'],
    priority: 1,
    statut: 'en_vigueur',
  },
  {
    numero: 'Art. 340 bis',
    titre: 'Sanctions spectacles',
    section: 'Taxe sur les spectacles, jeux et divertissements',
    impot: 'spectacles',
    themes: ['sanctions', 'pénalités', 'infractions'],
    priority: 2,
    statut: 'en_vigueur',
  },
];

/**
 * Récupère les métadonnées d'un article IL par son numéro
 */
export function getArticleMetadataIL(numero: string): ArticleMetadataIL | undefined {
  return ARTICLE_METADATA_IL.find(a => a.numero === numero || a.numero === `Art. ${numero}`);
}

/**
 * Récupère tous les articles d'un impôt spécifique
 */
export function getArticlesByImpot(impot: ArticleMetadataIL['impot']): ArticleMetadataIL[] {
  return ARTICLE_METADATA_IL.filter(a => a.impot === impot && a.statut === 'en_vigueur');
}

/**
 * Statistiques des articles IL
 */
export const IL_STATS = {
  total: ARTICLE_METADATA_IL.length,
  en_vigueur: ARTICLE_METADATA_IL.filter(a => a.statut === 'en_vigueur').length,
  abroges: ARTICLE_METADATA_IL.filter(a => a.statut === 'abroge').length,
  par_impot: {
    generalites: ARTICLE_METADATA_IL.filter(a => a.impot === 'generalites').length,
    cfpb: ARTICLE_METADATA_IL.filter(a => a.impot === 'cfpb').length,
    cfpnb: ARTICLE_METADATA_IL.filter(a => a.impot === 'cfpnb').length,
    dispositions_communes: ARTICLE_METADATA_IL.filter(a => a.impot === 'dispositions_communes').length,
    patente: ARTICLE_METADATA_IL.filter(a => a.impot === 'patente').length,
    taxe_regionale: ARTICLE_METADATA_IL.filter(a => a.impot === 'taxe_regionale').length,
    spectacles: ARTICLE_METADATA_IL.filter(a => a.impot === 'spectacles').length,
  },
};
