/**
 * Mapping des mots-cles vers les articles du CGI 2026
 * Chapitre 2 - IBA, IRCM, IRF, ITS (Art. 93 a 116A)
 *
 * REGLE : Le premier article de chaque liste est la SOURCE PRIMAIRE
 *
 * @author NORMX AI - CGI 242
 * @version 2026
 * @base Directive CEMAC n0119/25-UEAC-177-CM-42 du 09 janvier 2025
 */

export const KEYWORD_ARTICLE_MAP_IBA_2026: Record<string, string[]> = {

  // ========== IBA - CHAMP D'APPLICATION ==========
  'iba': ['Art. 93'],
  'impot benefices affaires': ['Art. 93'],
  'benefices affaires': ['Art. 93'],
  'personnes physiques imposables': ['Art. 93B'],
  'revenus imposables iba': ['Art. 93A'],
  'bic': ['Art. 93A'],
  'bnc': ['Art. 93A'],
  'benefices industriels commerciaux': ['Art. 93A'],
  'professions liberales': ['Art. 93A', 'Art. 94B'],
  'propriete intellectuelle': ['Art. 93A'],
  'residence fiscale iba': ['Art. 93B'],
  'domicile fiscal': ['Art. 93B'],
  '24 mois absence': ['Art. 93B'],
  'territorialite iba': ['Art. 93C'],

  // ========== IBA - BENEFICE IMPOSABLE ==========
  'benefice imposable iba': ['Art. 94'],
  'amortissement lineaire iba': ['Art. 94'],
  'report deficitaire iba': ['Art. 94'],
  '3 exercices deficit': ['Art. 94'],
  'charges non deductibles iba': ['Art. 94A'],
  'prelevements exploitant': ['Art. 94A'],
  'frais representation': ['Art. 94A'],
  '50% representation': ['Art. 94A'],
  'syscohada': ['Art. 94B'],
  'comptabilite engagement': ['Art. 94B'],
  'comptabilite caisse': ['Art. 94B'],

  // ========== IBA - MODALITES D'IMPOSITION ==========
  'taux iba': ['Art. 95'],
  '30% iba': ['Art. 95'],
  'minimum perception iba': ['Art. 95'],
  '1.5% minimum': ['Art. 95'],
  'deces exploitant': ['Art. 95A'],
  'report plus-value deces': ['Art. 95A'],
  'heritiers': ['Art. 95A'],
  'societes transparentes': ['Art. 95B'],
  'retenue source transparente': ['Art. 95B'],

  // ========== REGIME FORFAIT ==========
  'regime forfait': ['Art. 96'],
  'forfait': ['Art. 96'],
  'petites entreprises': ['Art. 96'],
  'seuil tva': ['Art. 96'],
  'option regime reel': ['Art. 96'],
  '1er fevrier option': ['Art. 96'],
  '3 ans option': ['Art. 96'],
  'professions reglementees': ['Art. 96'],
  'boulangers': ['Art. 96'],
  'grossistes': ['Art. 96'],
  'importateurs': ['Art. 96'],
  'smt': ['Art. 96A'],
  'systeme minimal tresorerie': ['Art. 96A'],
  'registres forfait': ['Art. 96A'],
  'evaluation forfaitaire': ['Art. 97'],
  'commission impots': ['Art. 97'],
  'impot global forfaitaire': ['Art. 98'],
  'declaration 294': ['Art. 98'],
  '15 fevrier forfait': ['Art. 98'],
  '100 000 amende registres': ['Art. 98'],
  'declaration fournisseurs': ['Art. 99'],
  '500 000 amende fournisseurs': ['Art. 99'],
  'taxation office': ['Art. 100', 'Art. 101'],

  // ========== REGIME REEL ==========
  'regime reel': ['Art. 102'],
  'benefice reel': ['Art. 102'],
  'teledeclaration': ['Art. 103'],
  'telepaiement': ['Art. 103'],
  '10% teledeclaration': ['Art. 103'],
  'expert-comptable': ['Art. 103'],
  'commissaire aux comptes': ['Art. 103'],
  'beac bilans': ['Art. 103'],
  'declaration statistique fiscale': ['Art. 104'],
  'etats financiers': ['Art. 104'],
  'ohada comptabilite': ['Art. 104'],
  '10 ans conservation': ['Art. 104'],

  // ========== IRCM - IMPOT REVENUS CAPITAUX MOBILIERS ==========
  'ircm': ['Art. 105'],
  'impot revenus capitaux mobiliers': ['Art. 105'],
  'revenus mobiliers': ['Art. 105'],
  'valeurs mobilieres': ['Art. 105'],
  'obligations': ['Art. 105', 'Art. 105C'],
  'creances': ['Art. 105', 'Art. 105D'],
  'plus-values mobilieres': ['Art. 105E'],
  'dividendes': ['Art. 105A'],
  'revenus distribues': ['Art. 105A'],
  'benefices reputes distribues': ['Art. 105A'],
  'conseil administration': ['Art. 105A'],
  'remboursement apports': ['Art. 105B'],
  'primes emission': ['Art. 105B'],
  'titres participatifs': ['Art. 105C'],
  'effets publics': ['Art. 105C'],
  'interets creances': ['Art. 105D'],
  'comptes courants ircm': ['Art. 105D'],
  'bons caisse': ['Art. 105D'],
  'cession actions': ['Art. 105E'],
  'cession parts sociales': ['Art. 105E'],
  'exoneration ircm': ['Art. 106'],
  'fusion ircm': ['Art. 106'],
  'apport partiel actif ircm': ['Art. 106'],
  'territorialite ircm': ['Art. 107'],
  '10% cession titres': ['Art. 107'],
  'fait generateur ircm': ['Art. 108'],
  '3 mois dividendes': ['Art. 108'],
  'base imposable ircm': ['Art. 109'],
  'moins-values mobilieres': ['Art. 109'],
  'taux ircm': ['Art. 110'],
  '15% ircm': ['Art. 110'],
  '35% revenus occultes': ['Art. 110'],
  'retenue ircm': ['Art. 110A'],

  // ========== IRF - IMPOT REVENUS FONCIERS ==========
  'irf': ['Art. 111'],
  'impot revenus fonciers': ['Art. 111'],
  'revenus fonciers': ['Art. 111'],
  'loyers': ['Art. 111'],
  'revenus locatifs': ['Art. 111'],
  'plus-values immobilieres': ['Art. 111', 'Art. 112'],
  'base imposable irf': ['Art. 111A'],
  'charges deductibles irf': ['Art. 111A'],
  'exonerations irf': ['Art. 111B'],
  'residence principale': ['Art. 111B'],
  '5 ans residence': ['Art. 111B'],
  'cession terrain': ['Art. 111C'],
  'prepondance immobiliere': ['Art. 111D'],
  '50% actif immobilier': ['Art. 111D'],
  '80% ca foncier': ['Art. 111E'],
  'taux irf': ['Art. 112'],
  '9% loyers': ['Art. 112'],
  '15% plus-values irf': ['Art. 112'],
  'retenue source irf': ['Art. 112A'],
  '15 mars retenue': ['Art. 112A'],
  'declaration irf': ['Art. 112B'],
  '60 jours cession': ['Art. 112B'],
  'fait generateur irf': ['Art. 113'],
  '3 mois bail': ['Art. 113'],
  'sous-location': ['Art. 113A'],

  // ========== ITS - IMPOT TRAITEMENTS SALAIRES ==========
  'its': ['Art. 114'],
  'impot traitements salaires': ['Art. 114'],
  'salaires': ['Art. 114'],
  'traitements': ['Art. 114'],
  'pensions': ['Art. 114'],
  'revenus salariaux': ['Art. 114'],
  '183 jours its': ['Art. 114'],
  'avantages en nature': ['Art. 114A'],
  'logement avantage': ['Art. 114A'],
  '20% logement': ['Art. 114A'],
  'domesticite': ['Art. 114A'],
  '7% domesticite': ['Art. 114A'],
  'voiture avantage': ['Art. 114A'],
  '3% voiture': ['Art. 114A'],
  'nourriture avantage': ['Art. 114A'],
  '20% nourriture': ['Art. 114A'],
  'eau eclairage': ['Art. 114A'],
  '5% eau eclairage': ['Art. 114A'],
  'telephone avantage': ['Art. 114A'],
  '2% telephone': ['Art. 114A'],
  'exonerations its': ['Art. 114B'],
  'indemnites exonerees': ['Art. 114B'],
  'base imposable its': ['Art. 114C'],
  'revenu net imposable its': ['Art. 114C'],
  'bareme its': ['Art. 114D'],
  '1 200 fcfa forfait': ['Art. 114D'],
  '10% tranche its': ['Art. 114D'],
  '15% tranche its': ['Art. 114D'],
  '20% tranche its': ['Art. 114D'],
  '30% tranche its': ['Art. 114D'],
  'charges famille its': ['Art. 114E'],
  'quotient familial': ['Art. 114E'],
  'personnes imposables its': ['Art. 115'],
  'retenue source its': ['Art. 116'],
  'employeur its': ['Art. 116'],
  'declaration its': ['Art. 116A'],
};

/**
 * Synonymes pour expansion de requetes CGI 2026 Chapitre 2
 */
export const SYNONYMS_IBA_2026: Record<string, string[]> = {
  'iba': ['impot sur les benefices d\'affaires', 'bic', 'bnc', 'benefices industriels'],
  'ircm': ['impot revenus capitaux mobiliers', 'dividendes', 'revenus mobiliers'],
  'irf': ['impot revenus fonciers', 'revenus locatifs', 'loyers'],
  'its': ['impot traitements salaires', 'salaires', 'irpp salarie'],
  'regime forfait': ['forfait', 'petites entreprises', 'micro-entreprises', 'smt'],
  'regime reel': ['benefice reel', 'comptabilite complete'],
  'residence fiscale': ['domicile fiscal', '183 jours', 'foyer habitation'],
  'avantages en nature': ['logement', 'voiture', 'nourriture', 'domesticite'],
  'plus-values': ['cession', 'mutation', 'gains en capital'],
  'retenue a la source': ['ras', 'prelevement', 'withholding tax'],
  'societe transparente': ['societe de personnes', 'snc', 'scs'],
};
